## docker compose file 
services:

  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"


  backend:
    build: ./backend
    # container_name: web3-backend   # avoid fixed container name for scaling / portability
    restart: unless-stopped
    # publish only on localhost (good for dev): "127.0.0.1:8005:8005"
    ports:
      - "127.0.0.1:8006:8005"
    # expose is optional, Compose network allows service-to-service comms
    expose:
      - "8005"
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=csblnbu@gmail.com                  # your Gmail address
      - SMTP_PASS=REMOVED_SMTP_APP_PASSWORD                  # Gmail App Password (not your login password)
      - MAX_UPLOAD_FILE_MB=50
      - MAX_UPLOAD_REQUEST_MB=100
      - RATE_LIMIT_CREATE_JOB_PER_MIN=10
      - RATE_LIMIT_RUN_INFERENCE_PER_MIN=20
    # healthcheck:
      # test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      # interval: 10s
      # timeout: 5s
      # retries: 5
    depends_on:
      - redis
      - postgres
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
    - ./backend/saved_models:/app/saved_models
    - ./backend/hf_cache:/app/hf_cache
    # user: "1001:1001" ##id -u #id -g #user: "${UID}:${GID}"



  celery-worker:
    build: ./backend
    command: celery -A celery_worker.celery worker --loglevel=info --max-tasks-per-child=1
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=csblnbu@gmail.com
      - SMTP_PASS=REMOVED_SMTP_APP_PASSWORD
    volumes:
      - ./backend/saved_models:/app/saved_models
      - ./backend/hf_cache:/app/hf_cache
    depends_on:
      - redis
      - backend
      - postgres
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # user: "1001:1001" # by using 



  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ppi_user
      POSTGRES_PASSWORD: ppi_pass
      POSTGRES_DB: ppi_jobs
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"


  frontend:
    build: ./frontend
    # container_name: web3-frontend
    restart: unless-stopped
    depends_on:
      - backend   # still only controls start order (health used to check readiness above)
    ports:
      - "127.0.0.1:8502:8501"
    environment:
      # - BACKEND_URL "http://backend:8005"
      - BACKEND_URL=http://backend:8005
    # Optionally mount code for live dev:
    # volumes:
    #   - ./frontend:/app




volumes:
  postgres_data:
